keepalived disabling feature
cloudfoundry-community/postgres-boshrelease pull request #24
Opened 2018-07-25 01:56 UTC by marcus-sds

I added at keepalived.enabled feature. 
Would you review and integrate?

2018-07-25 03:18 UTC, jhunt requested changes
You might not want to write '1' to the pid file; that will cause `monit stop keepalived` to kill -9 the init process, which may end up terminating the VM.

Instead, you probably want to put erb logic into the monit file, and skip the keepalived process altogether, followed by a huge if block around the guts of the `keepalived` bin script to just exit 1 if called (when keepalived isn't enabled).

2018-07-25 19:33 UTC, marcus-sds commented
kill -9 is also skipped. Anyway is it possible to put the erb logic at monit file? Then I will do that.

2018-07-27 09:40 UTC, marcus-sds commented
I updated monit

2018-07-27 12:29 UTC, jhunt approved these changes

2018-07-27 12:31 UTC, merged